import { PulseLine } from '@/components/brand/pulse-line'
import { Wordmark } from '@/components/brand/logo'
import { cn } from '@/lib/utils'

const CLINIC = {
  name: 'reMeet Hospital',
  address: 'House 42, Road 11, Dhanmondi, Dhaka 1209',
  phone: '+880 9610 445 500',
  email: 'care@remeet.health',
  licence: 'DGHS Licence 4472/2024',
}

/**
 * The shared paper for prescriptions and invoices.
 *
 * `data-print="sheet"` is what the print stylesheet keys off to strip the glass,
 * shadows, and positioning and hand the page over to the browser's A5 layout.
 * The letterhead rule is the pulse line flattened — the same motif that runs
 * through the app, doing the job a printed rule does.
 */
export function PrintSheet({
  docType,
  docCode,
  issuedOn,
  children,
  className,
}: {
  docType: string
  docCode: string
  issuedOn: string
  children: React.ReactNode
  className?: string
}) {
  return (
    <article
      data-print="sheet"
      className={cn(
        'glass mx-auto w-full max-w-[148mm] px-7 py-6 print:max-w-none print:px-0 print:py-0',
        className,
      )}
    >
      <header className="flex flex-col gap-3">
        <div className="flex items-start justify-between gap-6">
          <div className="flex items-center gap-2.5">
            <div className="flex flex-col">
              <Wordmark className="text-lg" />
              <p className="text-[0.6875rem] leading-tight text-ink-soft">{CLINIC.address}</p>
              <p className="font-mono text-[0.625rem] leading-tight text-ink-faint">
                {CLINIC.phone} · {CLINIC.email}
              </p>
            </div>
          </div>

          <div className="shrink-0 text-right">
            <p className="eyebrow text-ink-faint">{docType}</p>
            <p className="font-mono text-xs font-medium text-ink">{docCode}</p>
            <p className="font-mono text-[0.625rem] text-ink-faint">{issuedOn}</p>
          </div>
        </div>

        <PulseLine variant="rule" className="h-2.5 w-full text-ink/40" />
      </header>

      {children}

      <footer className="mt-6 border-t border-line pt-2.5">
        <p className="font-mono text-[0.5625rem] leading-relaxed text-ink-faint">
          {CLINIC.licence} · This document is generated by reMeet and is valid without a stamp.
        </p>
      </footer>
    </article>
  )
}

export { CLINIC }
